### ISSUE TITLE
the power of a negative number cause Java error on vdmj-4.4.6-P.jar

### ISSUE THREAD

**Issue by tomooda** [nickbattle/vdmj#63] opened 2022-08-12 09:42 UTC
`print (-1.23)**2` causes `Runtime: java.lang.ArithmeticException: Power of negative number; result would be complex` on VDMJ with high precision (vdmj-*-P.jar).
The same expression evaluates successfully on normal precision version of VDMJ.

**Comment by nickbattle** [comment] 2022-08-12 11:08
Thanks Tomo. Confirmed that I can reproduce it here. Will investigate...

**Comment by nickbattle** [comment] 2022-08-12 11:18
It looks like this is a bug in the Apfloat library that highprecision uses. It's been fixed in a later release, so I will patch this here too. The fix will go into 4.5.0-SNAPSHOT.

(Curiously, it works without the brackets around the negative number?)

**Comment by nickbattle** [comment] 2022-08-12 11:29
Hmm... the obvious fix doesn't work, so I will need to look more closely at updating Apfloat.

**Comment by tomooda** [comment] 2022-08-12 11:29
-1.23 ** 2 will be parsed as -(1.23**2) and evaluates -1.5129. (see the negative sign)
I know this parse is correct according to the LRM, but looks a little odd. :-)

**Comment by nickbattle** [comment] 2022-08-12 13:51
Hmm... yes, that's another one of those strange cases :-(

**Comment by nickbattle** [comment] 2022-08-12 15:32
I've written to the Apfloat maintainer. I think this is still a bug in the latest version of their library.

**Comment by nickbattle** [comment] 2022-08-12 18:12
So Mikko got back to me very quickly. This is a known issue and there are a couple of workarounds. I've applied one to VDMJ, so now we get the following result:
```
> p (-1.2)**2
= 1.44
Executed in 0.008 secs. 
```
I've pushed this to the highprecision branch, which is at 4.5.0-SNAPSHOT.

**Comment by tomooda** [comment] 2022-08-12 22:35
Thanks for the quick fix! 👍

**Closed** 2022-08-13 08:44 UTC
Labels: bug

**Comment by nickbattle** [comment] 2022-08-14 10:49
Incidentally, I've now taken this opportunity to update the Apfloat classes linked with VDMJ to the latest version, 1.10.1. This shouldn't make any functional difference, but it may be that some operations are faster.
